-- ImageTrace AI server-mediated schema
create extension if not exists pgcrypto;

create table if not exists public.analysis_jobs (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  image_sha256 text not null,
  file_name text,
  mime_type text,
  confirmed_public_name text,
  provider_status jsonb not null default '{}'::jsonb,
  result jsonb not null,
  created_at timestamptz not null default now()
);

create index if not exists analysis_jobs_user_created_idx
  on public.analysis_jobs(user_id, created_at desc);

alter table public.analysis_jobs enable row level security;
revoke all on table public.analysis_jobs from anon, authenticated;
grant select, insert, update, delete on table public.analysis_jobs to service_role;

drop policy if exists "Users can view own analysis" on public.analysis_jobs;
create policy "Users can view own analysis"
  on public.analysis_jobs
  for select
  to authenticated
  using ((select auth.uid()) = user_id);

-- Trusted Bangladesh Government source registry.
-- Sync with npm run sync-government-sources after configuring Supabase server credentials.
create table if not exists public.trusted_sources (
  id bigint generated by default as identity primary key,
  category text not null,
  name_bn text,
  name_en text,
  url text not null,
  domain text not null unique,
  source_url text,
  checked_on date,
  metadata jsonb not null default '{}'::jsonb,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists trusted_sources_domain_idx
  on public.trusted_sources(domain)
  where is_active = true;

create index if not exists trusted_sources_category_idx
  on public.trusted_sources(category)
  where is_active = true;

alter table public.trusted_sources enable row level security;
revoke all on table public.trusted_sources from anon, authenticated;
grant select, insert, update, delete on table public.trusted_sources to service_role;
